#include "ext_types.h"
static DataTypeInfo rtDataTypeInfoTable [ ] = { { "real_T" , 0 , 8 } , {
"real32_T" , 1 , 4 } , { "int8_T" , 2 , 1 } , { "uint8_T" , 3 , 1 } , {
"int16_T" , 4 , 2 } , { "uint16_T" , 5 , 2 } , { "int32_T" , 6 , 4 } , {
"uint32_T" , 7 , 4 } , { "boolean_T" , 8 , 1 } , { "fcn_call_T" , 9 , 0 } , {
"int_T" , 10 , 4 } , { "pointer_T" , 11 , 8 } , { "action_T" , 12 , 8 } , {
"timer_uint32_pair_T" , 13 , 8 } , { "physical_connection" , 14 , 8 } , {
"int64_T" , 15 , 8 } , { "uint64_T" , 16 , 8 } , { "mfrw1nqxwz" , 17 , 40 } ,
{ "icoaoz3rgd" , 18 , 1064 } , { "FILE*" , 19 , 160 } , { "doah2ritxs" , 20 ,
4 } , { "iotyzgkdcn" , 21 , 12 } , { "uint64_T" , 22 , 8 } , { "int64_T" , 23
, 8 } , { "uint_T" , 24 , 32 } , { "char_T" , 25 , 8 } , { "uchar_T" , 26 , 8
} , { "time_T" , 27 , 8 } } ; static uint_T rtDataTypeSizes [ ] = { sizeof ( real_T ) , sizeof ( real32_T ) , sizeof ( int8_T ) , sizeof ( uint8_T ) , sizeof ( int16_T ) , sizeof ( uint16_T ) , sizeof ( int32_T ) , sizeof ( uint32_T ) , sizeof ( boolean_T ) , sizeof ( fcn_call_T ) , sizeof ( int_T ) , sizeof ( pointer_T ) , sizeof ( action_T ) , 2 * sizeof ( uint32_T ) , sizeof ( int32_T ) , sizeof ( int64_T ) , sizeof ( uint64_T ) , sizeof ( mfrw1nqxwz ) , sizeof ( icoaoz3rgd ) , sizeof ( int32_T ) , sizeof ( doah2ritxs ) , sizeof ( iotyzgkdcn ) , sizeof ( uint64_T ) , sizeof ( int64_T ) , sizeof ( uint_T ) , sizeof ( char_T ) , sizeof ( uchar_T ) , sizeof ( time_T ) } ; static const char_T * rtDataTypeNames [ ] = { "real_T" , "real32_T" , "int8_T" , "uint8_T" , "int16_T" , "uint16_T" , "int32_T" , "uint32_T" , "boolean_T" , "fcn_call_T" , "int_T" , "pointer_T" , "action_T" , "timer_uint32_pair_T" , "physical_connection" , "int64_T" , "uint64_T" , "mfrw1nqxwz" , "icoaoz3rgd" , "FILE*" , "doah2ritxs" , "iotyzgkdcn" , "uint64_T" , "int64_T" , "uint_T" , "char_T" , "uchar_T" , "time_T" } ; static DataTypeTransition rtBTransitions [ ] = { { ( char_T * ) ( & rtB . cqzfaecv4m ) , 0 , 0 , 595 } , { ( char_T * ) ( & rtB . bxq1yx2osy ) , 8 , 0 , 2 } , { ( char_T * ) ( & rtDW . gocvwhon5y ) , 18 , 0 , 1 } , { ( char_T * ) ( & rtDW . mznmhfvmea [ 0 ] ) , 19 , 0 , 20 } , { ( char_T * ) ( & rtDW . mhyvkdo2ux ) , 17 , 0 , 1 } , { ( char_T * ) ( & rtDW . mzifbxk1wn ) , 21 , 0 , 1 } , { ( char_T * ) ( & rtDW . lo3qyprm4b ) , 0 , 0 , 1432 } , { ( char_T * ) ( & rtDW . db0zscnkw5 ) , 11 , 0 , 10 } , { ( char_T * ) ( & rtDW . cel4kex0vf ) , 6 , 0 , 5 } , { ( char_T * ) ( & rtDW . abxfrplp1i ) , 20 , 0 , 1 } , { ( char_T * ) ( & rtDW . oeoydvlwgx . PrevIndex ) , 10 , 0 , 1 } , { ( char_T * ) ( & rtDW . npi2ladrba ) , 8 , 0 , 1 } , { ( char_T * ) ( & rtDW . ieyig5nl2r ) , 2 , 0 , 16 } , { ( char_T * ) ( & rtDW . elg2z4i5mu ) , 8 , 0 , 42 } } ; static DataTypeTransitionTable rtBTransTable = { 14U , rtBTransitions } ; static DataTypeTransition rtPTransitions [ ] = { { ( char_T * ) ( & rtP . Q [ 0 ] ) , 0 , 0 , 83 } , { ( char_T * ) ( & rtP . DetectChange1_vinit ) , 8 , 0 , 1 } , { ( char_T * ) ( & rtP . PulseGenerator_Amp ) , 0 , 0 , 88 } , { ( char_T * ) ( & rtP . RT7_InitialCondition ) , 8 , 0 , 1 } , { ( char_T * ) ( & rtP . VariableIntegerDelay_DiagnosticForDelayLength ) , 3 , 0 , 1 } } ; static DataTypeTransitionTable rtPTransTable = { 5U , rtPTransitions } ;
